### ISSUE TITLE
Offer to help

### ISSUE THREAD

**Issue by maxnordlund** [chaijs/loupe#13]
Hi, prompted by https://github.com/chaijs/chai/issues/662#issuecomment-441997501 I took a look at this repo, but there hasn't been any activity for a while. I guess it's on someones computer, but I thought I should offer to help.

**Comment by keithamus** [comment]
Yes, sadly I broke the cardinal sin of using git! I left the new code on my machine and then my Mac went to the apple store and they formatted my machine despite me telling them not to!

Help is definitely welcome! The biggest drag I had during development was writing tests to catch all the conditions we’d hit.

I’ll come back to this issue in a bit with an action plan on what to do next.

**Comment by maxnordlund** [comment]
> Yes, sadly I broke the cardinal sin of using git! I left the new code on my machine 

Haven't we all 😉 but ...

> ... and my Mac went to the apple store and they formatted my machine despite me telling them not to!

That's a real bummer 😿 

> Help is definitely welcome! The biggest drag I had during development was writing tests to catch all the conditions we’d hit.

Tests sounds like fun, and that's something I can definitely contribute once I've seen an example. I guess we could make it super easy using some sort of factory/helper? I can happily write one of those we the time comes. _(I have been writing custom assertions for a private project and it's been a real treat to make my tests look ✨ nice ✨)_

> I’ll come back to this issue in a bit with an action plan on what to do next.

Good, I'm looking forward to it. In the other issue I linked to node's current inspect implementation, I think a fair amount can be borrowed from there. To cut down on the work, right?

**Comment by keithamus** [comment]
Closing this in favour of #15
