### ISSUE TITLE
Time representation difference in Chai.js

### ISSUE THREAD

**Issue by flaambe** [chaijs/loupe#34]
Is it better to change the time representation in loupe or chai.js tests?

```bash
  21) should
       most(n) (dates):

      expected 'blah
      + expected - actual

      -blah: expected 2021-01-27T09:34:22.030Z to be at most 2021-01-27T09:34:21.030Z
      +blah: expected Wed, 27 Jan 2021 09:34:22 GMT to be at most Wed, 27 Jan 2021 09:34:21 GMT
      
      at globalErr (test/bootstrap/index.js:52:57)
      at Context.<anonymous> (test/should.js:1128:5)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by keithamus** [comment]
Let's change it here - ISO dates lead to less confusion.

**Comment by flaambe** [comment]
I think you meant in chai, since loupe uses ISO, or I'm wrong?))

**Comment by keithamus** [comment]
Oh yeah :sweat_smile: I was reading it wrong. Let's change chai :smile:

**Comment by flaambe** [comment]
I can't figure out what the problem is:
```bash

**Comment by keithamus** [comment]
https://github.com/chaijs/chai/blob/23764f340d6d3796eafdb7a9869b423bc45e0c8b/lib/chai/core/assertions.js#L1569

this probably needs to change to something like

```js
range = loupe(start) + '..' + loupe(finish)
```

**Comment by flaambe** [comment]
@keithamus Yeah, thanks, it worked
