### ISSUE TITLE
Loupe doesn't work correctly for buffers 

### ISSUE THREAD

**Issue by flaambe** [chaijs/loupe#35]
Example:
```js
inspect(Buffer.from([2,3,4]))
```
returns
```bash
'Buffer[ 2, 34,  ]'
```
I think the problem is on the line: https://github.com/chaijs/loupe/blob/32b72766a6da738aa11438495d3b461f98942eda/lib/typedarray.js#L27

**Comment by keithamus** [comment]
@flaambe are you writing up a test for this case? Or shall I?
