### ISSUE TITLE
Return value for number 0

### ISSUE THREAD

**Issue by flaambe** [chaijs/loupe#37]
I wanted to know why we return +0 or -0? In chai we just use 0.
https://github.com/chaijs/loupe/blob/0c75417f33f1a4aecb7fcafff6e5938a2727b753/lib/number.js#L15

```bash
3) expect
    empty:

      AssertionError: expected '.empty was passed non-string primitive +0' to equal '.empty was passed non-string primitive 0'
      + expected - actual

      -.empty was passed non-string primitive +0
      +.empty was passed non-string primitive 0
      
      at globalErr (test/bootstrap/index.js:52:57)
      at Context.<anonymous> (test/expect.js:1597:5)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by keithamus** [comment]
This is important because many tests assert the difference between `+0`/`-0`. We should update Chai to reflect this change.

**Comment by flaambe** [comment]
And one more question, it seems custom functions don't work, or I have to pass some parameters?
```bash
5) utilities
       inspect with custom stylize-calling inspect()s:

      AssertionError: expected '{ outer: { inspect: [Function inspect] } }' to equal '{ outer: Object content }'
      + expected - actual

      -{ outer: { inspect: [Function inspect] } }
      +{ outer: Object content }
```

**Comment by keithamus** [comment]
This is a change in the `loupe` API to avoid surprising behaviours for calls that have an `inspect` function that you aren't aware of. The behaviour is opt in now, so you need to pass `customInspect: true`, e.g `loupe(obj, { customInspect: true })`. We can do that inside Chai to avoid breaking change, and turn it off in Chai 5.

**Comment by flaambe** [comment]
I tried to pass this parameter, but it seems the execution does not reach this line:
https://github.com/chaijs/loupe/blob/0c75417f33f1a4aecb7fcafff6e5938a2727b753/index.js#L142
so the result is the same.

**Comment by keithamus** [comment]
Ahh yeah its because of this above:

https://github.com/chaijs/loupe/blob/0c75417f33f1a4aecb7fcafff6e5938a2727b753/index.js#L129-L133

We should verify this behaviour works well in Loupe and release a patch. The block I linked above should add `!customInspect &&` as an extra conditional, IMO.
