### ISSUE TITLE
Loupe is creating wrongly-formed strings when inspecting some strings

### ISSUE THREAD

**Issue by dubzzz** [chaijs/loupe#78]
The current implementation of `inspect` tends to cut surrogate-pairs at the middle producing invalid unicode strings.

For example the string produced by the snippet below is invalid:

```js
const { inspect } = require('loupe')
inspect('🐱🐱🐱', {truncate: 6})
// '🐱\ud83d…'
```

Indeed `\ud83d` alone does not make sense for unicode. For instance `encodeURI('\ud83d')` will report the error: Uncaught URIError: malformed URI sequence.

**Comment by dubzzz** [comment]
If you're are ok with an external contribution on this problem I can try to work on a fix in the coming days.

**Comment by keithamus** [comment]
Thanks for the report. It'd be great to see a contribution for a fix here.

**Comment by dubzzz** [comment]
PR opened
